local path = require("fre.path")

describe("fre.path", function()
  it("normalizes POSIX paths lexically", function()
    assert.are.equal("/srv/project/file", path.normalize("/srv/project/./cache/../file"))
    assert.are.equal("/", path.normalize("/../../"))
    assert.are.equal("a/b", path.normalize_relative("a/./cache/../b"))
    assert.are.equal("a/b", path.normalize_relative("a\\cache\\..\\b", { windows = true }))
  end)

  it("resolves children directly under the POSIX filesystem root", function()
    assert.are.equal("/child", path.resolve("/", "child"))
  end)

  it("validates editable targets under the POSIX filesystem root", function()
    local absolute, relative = path.edit_target("/", "child")
    assert.are.equal("/child", absolute)
    assert.are.equal("child", relative)
  end)

  it("generates temporary siblings directly under the POSIX filesystem root", function()
    assert.are.equal("/.file.fre-tmp-root", path.temporary_sibling("/file", nil, "root"))
  end)

  it("normalizes drive and UNC paths without filesystem access", function()
    assert.are.equal("C:/Users/Work", path.normalize("c:\\Users\\Temp\\..\\Work"))
    assert.are.equal("C:/", path.normalize("c:/../../"))
    assert.are.equal("//server/share/folder", path.normalize("\\\\server\\share\\folder\\..\\folder"))
    assert.are.equal("//server/share", path.normalize("//server/share/folder/.."))
  end)

  it("uses path components for containment", function()
    assert.is_true(path.contains("/project", "/project/src/file"))
    assert.is_true(path.contains("/project", "/project"))
    assert.is_false(path.contains("/project", "/project-old/file"))
    assert.is_true(path.contains("C:/Project", "c:/project/src"))
    assert.is_false(path.contains("C:/Project", "D:/Project/src"))
    assert.are.equal("src/file", path.relative("C:/Project", "c:/project/src/file"))
  end)

  it("does not mistake a drive path for a URI", function()
    assert.is_false(path.is_uri("C:/work/file"))
    assert.is_false(path.is_uri("c:relative"))
    assert.is_true(path.is_uri("file:///work/file"))
    assert.is_true(path.is_uri("ssh://host/path"))
  end)

  it("compares Windows paths with practical ASCII case folding", function()
    assert.is_true(path.equal("C:/Data/FILE", "c:\\data\\file"))
    assert.is_false(path.equal("C:/Data/FILE", "c:/data/file.txt"))
    assert.is_false(path.equal("C:/caf\195\169", "c:/CAF\195\137"))
  end)

  it("validates and normalizes editable root-relative targets", function()
    local absolute, relative = path.edit_target("C:/Project", "src\\..\\new-file")
    assert.are.equal("C:/Project/new-file", absolute)
    assert.are.equal("new-file", relative)
    assert.has_error(function()
      path.edit_target("/project", "")
    end)
    assert.has_error(function()
      path.edit_target("/project", "/absolute")
    end)
    assert.has_error(function()
      path.edit_target("/project", "../escape")
    end)
    assert.has_error(function()
      path.edit_target("/project", "C:/other")
    end)
    assert.has_error(function()
      path.edit_target("C:/Project", "\\rooted")
    end)
    assert.has_error(function()
      path.edit_target("/project", "https://example.test")
    end)
    assert.has_error(function()
      path.edit_target("/project", "file\nname")
    end)
  end)

  it("avoids known temporary sibling collisions", function()
    local first = "/tmp/.file.fre-tmp-token"
    local candidate = path.temporary_sibling("/tmp/file", { [first] = true }, "token")
    assert.are.equal("/tmp/.file.fre-tmp-token-1", candidate)
    assert.is_false(path.equal(candidate, first))
  end)

  it("rejects CR and LF in values that need one buffer line", function()
    assert.are.equal("plain", path.assert_single_line("plain"))
    assert.has_error(function()
      path.assert_single_line("line\rbreak")
    end)
    assert.has_error(function()
      path.normalize("line\nbreak")
    end)
  end)
end)
